# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.5
os:
  - linux
  - osx
# arch:
#   - x64
cache:
  directories:
    - ~/.julia/artifacts
jobs:
  fast_finish: true
  # allow_failures:
  #   - julia: 1.5

branches:
  only:
  - master

# jobs:
#   include:
#     - stage: "Documentation"
#       julia: 1.5
#       os:
#         - linux
#         - osx
#       script:
#         - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
#                                                Pkg.instantiate()'
#         - julia --project=docs/ docs/make.jl
#       after_success: skip
