# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.4
  - nightly
os:
  - linux
  - osx
  - windows
arch:
  - x64
cache:
  directories:
    - ~/.julia/artifacts
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
